-- MySQL Script generated by MySQL Workbench
-- Thu Nov  6 12:58:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema detran
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema detran
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `detran` DEFAULT CHARACTER SET utf8 ;
USE `detran` ;

-- -----------------------------------------------------
-- Table `detran`.`Proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Proprietario` (
  `CPF` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Endereco` VARCHAR(250) NOT NULL,
  `Bairro` VARCHAR(250) NOT NULL,
  `Cidade` VARCHAR(250) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Modelo` (
  `idModelo` INT NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idModelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Veiculo` (
  `Placa` VARCHAR(7) NOT NULL,
  `Chassi` VARCHAR(17) NOT NULL,
  `cor` VARCHAR(250) NOT NULL,
  `Ano_fabricado` YEAR(4) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Modelo_idModelo` INT NOT NULL,
  `Proprietario_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`Placa`, `Categoria_idCategoria`, `Modelo_idModelo`),
  INDEX `fk_Veiculo_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Veiculo_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  INDEX `fk_Veiculo_Proprietario1_idx` (`Proprietario_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `detran`.`Categoria` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Veiculo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `detran`.`Modelo` (`idModelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Veiculo_Proprietario1`
    FOREIGN KEY (`Proprietario_CPF`)
    REFERENCES `detran`.`Proprietario` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Telefones` (
  `id_telefone` INT NOT NULL,
  `Numero_telefone` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(250) NULL,
  `Proprietario_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_telefone`, `Proprietario_CPF`),
  INDEX `fk_Telefones_Proprietario1_idx` (`Proprietario_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Telefones_Proprietario1`
    FOREIGN KEY (`Proprietario_CPF`)
    REFERENCES `detran`.`Proprietario` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Agente` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `data_contratacao` DATE NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Tipo_infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Tipo_infracao` (
  `idTipo_infracao` INT NOT NULL,
  `valor` INT NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idTipo_infracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Local` (
  `longitude` DECIMAL(10,7) NOT NULL,
  `latitude` DECIMAL(10,7) NOT NULL,
  `velocidade_permitida` INT NOT NULL,
  PRIMARY KEY (`longitude`, `latitude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detran`.`Infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detran`.`Infracao` (
  `idInfracao` INT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `velocidade_aferida` INT NOT NULL,
  `Agente_matricula` INT NOT NULL,
  `Tipo_infracao_idTipo_infracao` INT NOT NULL,
  `Local_longitude` DECIMAL(10,7) NOT NULL,
  `Local_latitude` DECIMAL(10,7) NOT NULL,
  `Veiculo_Placa` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idInfracao`, `Agente_matricula`, `Tipo_infracao_idTipo_infracao`, `Local_longitude`, `Local_latitude`, `Veiculo_Placa`),
  INDEX `fk_Infracao_Tipo_infracao1_idx` (`Tipo_infracao_idTipo_infracao` ASC) VISIBLE,
  INDEX `fk_Infracao_Local1_idx` (`Local_longitude` ASC, `Local_latitude` ASC) VISIBLE,
  INDEX `fk_Infracao_Veiculo1_idx` (`Veiculo_Placa` ASC) VISIBLE,
  INDEX `fk_Infracao_Agente1_idx` (`Agente_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Infracao_Agente1`
    FOREIGN KEY (`Agente_matricula`)
    REFERENCES `detran`.`Agente` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Infracao_Tipo_infracao1`
    FOREIGN KEY (`Tipo_infracao_idTipo_infracao`)
    REFERENCES `detran`.`Tipo_infracao` (`idTipo_infracao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Infracao_Local1`
    FOREIGN KEY (`Local_longitude` , `Local_latitude`)
    REFERENCES `detran`.`Local` (`longitude` , `latitude`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Infracao_Veiculo1`
    FOREIGN KEY (`Veiculo_Placa`)
    REFERENCES `detran`.`Veiculo` (`Placa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
